# GrimAC main configuration
# Source code: https://github.com/MWHunter/Grim
# Copyright 2022 DefineOutside and contributors, Licensed under GPLv3.
# Modified binaries, or plugins with copied Grim code, must be private,
# or with full source code available to buyers at no additional cost.

alerts:
  # Should players with grim.alerts permission automatically enable alerts on join?
  enable-on-join: true
  # In addition to broadcasting alerts to players, should they also be sent to the console?
  print-to-console: true

client-brand:
  # This means it won't broadcast their brand to operators if the brand matches the following regexes
  ignored-clients:
    - "^vanilla$"
    - "^fabric$"
    - "^lunarclient:[a-z0-9]{7}"
    - "^Feather Fabric$"

spectators:
  # Hide all spectators with the grim.spectator permission regardless if they are actually actively spectating
  hide-regardless: false
  # Will make spectators hidden only in these worlds, keep blank to allow all worlds
  allowed-worlds:
    - ""

# How long should players have until we keep them for timing out?
max-ping: 120

# Set to false if your server uses custom resource packs
# Example: Cops & Robbers on Hypixel
using-custom-resource-packs: false

# Check Settings
Simulation:
  setback-decay-multiplier: 0.999
  threshold: 0.001
  immediate-setback-threshold: 0.1
  max-advantage: 1
  max-ceiling: 4

Phase:
  setback-vl: 1
  decay: 0.005
  dont-alert-until: 10
  alert-interval: 10

NoSlowdown:
  threshold: 0.001
  setback-vl: 5
  decay: 0.05
  dont-alert-until: 25
  alert-interval: 25

Knockback:
  threshold: 0.001
  setback-vl: 3
  decay: 0.025
  dont-alert-until: 8
  alert-interval: 5

Explosion:
  threshold: 0.001
  setback-vl: 3
  decay: 0.025
  dont-alert-until: 8
  alert-interval: 5

EntityControl:
  decay: 0.05
  setbackvl: 25
  dont-alert-until: 40
  alert-interval: 40

Reach:
  threshold: 0.0005
  block-impossible-hits: true
  # Enable if your server is 1.8.x, otherwise leave disabled.
  enable-post-packet: false

debug-pipeline-on-join: false

config-version: 4